name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js (for version extraction)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get version from package.json
      id: get-version
      run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ steps.get-version.outputs.version }}
        docker tag ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ steps.get-version.outputs.version }} ${{ secrets.DOCKER_HUB_USER }}/projectalogs:latest

    - name: Test Docker image (dry run)
      run: |
        docker run --rm ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ steps.get-version.outputs.version }} node -v
        docker run --rm ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ steps.get-version.outputs.version }} node dist/main.js &
        sleep 5 && curl -f http://localhost:3000 || (echo "App test failed" && exit 1)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ steps.get-version.outputs.version }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/projectalogs:latest
