name: Build and Push Docker image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install

    - name: Get version from package.json
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --tag ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ env.VERSION }}
        docker tag ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ env.VERSION }} ${{ secrets.DOCKER_HUB_USER }}/projectalogs:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/projectalogs:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/projectalogs:latest
